server:
  port: 9527
spring:
  application:
    name: euretzuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tick.serviceId: EURETICK
    tick.path: /mytick/**
  ignored-services: EURETICK

