server:
  port: 8761
eureka:
  instance:
    hostname: eurkaserver1
  client:
    service-url:
      defaultZone: http://eurkaserver2:8762/eureka/,http://eurkaserver3:8763/eureka/
    fetch-registry: false
    register-with-eureka: false
