server:
  port: 80
spring:
  application:
    name: service-hi-ha
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
    register-with-eureka: false
  instance:
    instance-id: user192.168.1.19:80
